application: closure-kitchen-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /files
  static_dir: files
  expiration: 1h

- url: /closure-library
  static_dir: closure-library
  expiration: 24h

- url: /docs/.*
  script: docs.py

- url: /.*
  script: main.py
